#!/bin/bash -x
yaml_content=$'apiVersion: apps/v1\n'
yaml_content+=$'kind: Deployment\n'
yaml_content+=$'metadata:\n'
yaml_content+=$'  name: quiz2-app\n'
yaml_content+=$'spec:\n'
yaml_content+=$'  replicas: 2\n'
yaml_content+=$'  selector:\n'
yaml_content+=$'    matchLabels:\n'
yaml_content+=$'      app: quiz2-app\n'
yaml_content+=$'  template:\n'
yaml_content+=$'    metadata:\n'
yaml_content+=$'      labels:\n'
yaml_content+=$'        app: quiz2-app\n'
yaml_content+=$'    spec:\n'
yaml_content+=$'      containers:\n'
yaml_content+=$'      - name: my-container\n'
yaml_content+=$'        image: nginx:lates\n'
yaml_content+=$'        ports:\n'
yaml_content+=$'        - containerPort: 80\n'
yaml_content+=$'        resources:\n'
yaml_content+=$'          requests:\n'
yaml_content+=$'            memory: "1Gi"\n'
yaml_content+=$'            cpu: "1000m"\n'
yaml_content+=$'          limits:\n'
yaml_content+=$'            memory: "500Mi"\n'
yaml_content+=$'            cpu: "500m"\n'
yaml_content+=$'        volumeMounts:\n'
yaml_content+=$'        - mountPath: "/data"\n'
yaml_content+=$'          name: my-volume\n'
yaml_content+=$'      volumes:\n'
yaml_content+=$'      - name: my-volume\n'
yaml_content+=$'        persistentVolumeClaim:\n'
yaml_content+=$'          claimName: non-existent-pvc\n'


echo "$yaml_content" > quiz2.yaml
kubectl apply -f quiz2.yaml
